# Generated by Django 4.1.7 on 2023-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_article_options_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Публікація', 'verbose_name_plural': 'Публікації'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
    ]
