# Generated by Django 4.1.7 on 2023-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_article_options_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Блоґ')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Блоґ',
                'verbose_name_plural': 'Блоґи',
            },
        ),
    ]
